# Frontend section
frontend:
  replicaCount: 1
  revisionHistoryLimit: 1
  image:
    repository: loyboi600
    tag: mywebappfrontend:v1.0.0
    pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 200m
        memory: 300Mi
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
  service:
    name: frontend
    type: NodePort
    servicePort: 80

# Backend section
backend:
  replicaCount: 1
  revisionHistoryLimit: 1
  image:
    repository: loyboi600
    tag: mywebappbackend:v1.0.0
    pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 200m
        memory: 300Mi
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
  service:
    name: backend
    type: NodePort
    servicePort: 8080
    secret: mysecretstring
    
# Postgre section     
postgresql:
  enabled: true
  global:
    postgresql:
      postgresqlDatabase: postgres
      postgresqlUsername: postgres
      servicePort: 5432
