apiVersion: v1
kind: Service
metadata:
  name: "backend-service"
spec:
  ports:
  - name: http
    protocol: TCP
    port: 9000
    targetPort: {{ .Values.backend.service.servicePort }}
  type: {{ .Values.backend.service.type }}
  selector:
    app: "backend-selector"
