apiVersion: v1
kind: Service
metadata:
  name: "backend-service"
spec:
  ports:
  - name: http
    port: {{ .Values.backend.service.servicePort }}
    nodePort: 9000
  type: {{ .Values.backend.service.type }}
  selector:
    app: "backend-selector"
