apiVersion: v1
kind: Service
metadata:
  name: "frontend-service"
spec:
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: {{ .Values.frontend.service.servicePort }}
  type: {{ .Values.frontend.service.type }}
  selector:
    app: "frontend-selector"
