apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: my-ingress
spec:
  rules:
  - host: mywebapp.local
    http:
      paths:
      - path: /
        backend:
          serviceName: api-service
          servicePort: 80